//! Low-level bindings to SWI Prolog.
//!
//! Generated by bindgen.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

extern crate gmp_mpfr_sys;
extern crate ncurses;

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
